### ISSUE TITLE
btlike库找不到

### ISSUE THREAD

**Issue by sunny-tong** [xgfone/gobt#1]
github.com/btlike/repository 这个库现在找不到了

**Comment by xgfone** [comment]
@sunny-tong 是的，之前我已发现 @btlike 这个账号已被注销掉了。之后，我抽空把这些依赖更换掉就好了。

**Comment by xgfone** [comment]
@sunny-tong 我已经把缺失的 github.com/btlike/repository 放到 vendor 中，直接 `go get  github.com/xgfone/gobt`，之后会提失 github.com/btlike/repository 依赖的某些库缺失，再次通过 `go get` 把这些缺少的库获取一下即可。之所以会出现这个情况，是因为 github.com/btlike/repository 位于 vendor 目录下，`go get` 不会去自动获取它的依赖包。

**NOTICE：** 这个仓库不再维护，仅作为学习用。

**Comment by sunny-tong** [comment]
@xgfone 感谢
